name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Linux x86_64
      run: cargo build --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: RealFS-linux-x86_64
        path: ./target/release/realfs
    - name: Add Windows build target
      run: |
        sudo apt-get install -y mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Build Windows x86_64
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
      with:
        name: RealFS-windows-x86_64
        path: ./target/x86_64-pc-windows-gnu/release/realfs.exe
